namespace Cogitatio.Models;

/// <summary>
/// Data generated by the browser during a Proof of Work request
/// Include ProofOfWork component and that's all you need 
/// </summary>
public class PoWResult
{
    /// <summary>
    /// the nonce is created
    /// </summary>
    public long Nonce { get; set; }
    public string Challenge { get; set; } = string.Empty;
}